# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				sheep = true
				rabbit = true
				creeper = true
				skeleton = true
				bat = true
				spider = true
				zombie = true
				item = true
				enderman = true
				cow = true
				glow_squid = true
				squid = true
				tropical_fish = true
				pufferfish = true
				turtle = true
				pig = true
				slime = true
				husk = true
				witch = true
				villager = true
				frog = true
				dolphin = true
				cod = true
				zombie_villager = true
				chicken = true
				salmon = true
				drowned = true
				cave_spider = true
				llama = true
				experience_orb = true
				bee = true

			[light_sources.settings.entities.cobblemon]
				pokemon = true

			[light_sources.settings.entities.immersive_aircraft]
				biplane = true
				airship = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.artifacts]
				mimic = true

